* 今天感冒了，早上忽略了五点的闹钟，直接睡到了七点，吃了点早餐，也就没有去跑步，到公司以后量了一下体温，36.6，不算发烧，但是温度也不低，整天发困，无精打采，头昏脑涨，情绪低落。

不是那么想许言了，上午她发来学习的照片，我也懒得回微信，一直觉得冷，在屋里都穿着外套，有时还会带上帽子，
公司还有几个人有发烧的症状，可能都被累的差不多了，昨晚绍彦用邮件发来了一份前端简历，两个信息，一个是以后得技术都在上海，另一个是再招一个前端。
今天算是走得早一些，六点半就走了，剩下的一些优化，等到明天再搞
\
\
心之所向依旧是许言，但是今天不太思念，原因两点，一个是生病影响情绪，另一个就是感觉她对我连一个朋友应有的关心都没有，完全没有一丝好奇，对于我的经历，我的情况，我的状态，我的心情，甚至我的姓名，略感失望。也许我只是一个工具吧，对于这样的她我还要继续喜欢她吗？
所有的话题都是围绕着她，她之外的事情她从来不过问也不关心，我还要喜欢她吗？
我还要继续喜欢她吗？我喜欢的是她这个人，还是这个人和她对我的态度，还是喜欢她对我的感情？我不能期望她能改变，也许不止对我，对所有人她都是这种态度，我该怎么办。
我之前的恋爱都是因为对方喜欢我，我想这一次，我要继续喜欢她，即使现在她这个态度，他这个态度主要还是因为不喜欢我的，所以即使我再喜欢他，再没有感受到他对我的喜欢，之前我也不会真正的表白的，也不可能。发起最后的进攻。我觉得现在的方向应该是这样的，我继续做自己可以去关心她，可以去帮助她也可以。让他成为一个更好的自己，也可以让他感受到我对她的喜欢。但是不能让他觉得我。我的世界里只有他。我觉得应该还得再跟他保持一定的距离，朋友以及朋友以上。不能再多了。对他的关心也只停留在朋友的级别。不能让他觉得已经吃定我了。如果一直喜欢下去三个月100天吧，认识他100天，从认识他开始算100天的时间，如果还是不能感受到他的喜欢的话。那我就会放弃喜欢他转而只做普通朋友，就像在抖音里面听到的那句话，但你挂账的时候拐到了一个谢字，你还会继续刮下去吗？我觉得100天的时间足够怪出第一个字来了。
\
说。今天不想理他。但是我还是很自然地去翻了一下他的朋友圈，发现他今天没有发朋友圈。我今天跑完步我也不能发朋友圈。说测试卖的算不上测试。就是我决定要两天。没有动静。看一下他是否真的只是永远关心他自己。他是否会考虑到我？也许会也许不会。但是不管怎样，这个结果不会成为。我对他的态度的依据。因为这根本说明不了什么问题。因为我现在已经知道他不喜欢我。甚至连朋友之间的友情都算不上。作为朋友我觉得知道一个真名。或是一个最起码的尊重吧。虽然说那一天他是没有听清楚，因为是在提出。但是他之后却没有再问过。也没有表示过。在乎我叫什么？所以我觉得很不爽。在我类似这种感受不到喜欢的时候。即使他主动的想要和我确立关系，我也肯定不会答应的，因为我不能在我感受不到。喜欢的时候。就去开谁的关系，这是极其不负责任的表现。我也不能那么傻。我决定要去跑个5km。然后回来洗个热水澡。在吃个饭。看会视频就睡觉了。希望我的感冒能好一点，明天那是一个元气满满的一天。
\
\
下午准备下班的时候，我听到精华很小声的说了一句。就是吐槽了一句吧。然后我就问他怎么回事儿，然后他就说他和子东之间的一些小矛盾。可是我能怎么说呢？我就只能是听着呗。矛盾这种事情办公室里面也经常见吧。不过还是不要上心就好。如果非要朝身上使的话，确实能找到很多的这种。可以爆发的点。
*