* 梦到许言，在梦里连续好几天，每天在大操场看室外电影，每次都看到剩下我们两个人，住宿的话是上下铺的学生宿舍，有一天我爬上了她的床，她让我把腿张开，她躺在我的怀里身上。几十秒之后就下床了。

\
最后一天吃完饭，她用纸写了很多对我说的话，说我对她的好她都看在眼里，并且这几天的活动也让她更加了解我了，说是让我给她按摩一下眼睛，我正要下手按的时候，醒了
\
\
[[file:%E6%97%A5%E8%AE%B0-2019-12-26.resources/12%E6%9C%8826%E6%97%A5%E7%9A%84%E6%97%A5%E8%AE%B0.mp3]]
\
\
今天早上五点半起床，
\
墨迹到六点出的门。一路小跑。一路慢跑，
\
一边在思考一边的回忆，一边在跑步跑步跑的特别的慢，
\
将近跑了一个小时。
\
跑完步之后，回到家压压腿拉伸一下，然后又用泡沫轴放松一下，
\
然后再做个护肤磨叽磨叽就到了该出门的时候了，一早上的时间两个多小时感觉还是不够用，可能还是由于我太磨叽，如果不是因为墨迹，时间还是足够的。
\
上午公司里面主要是开会了，开的是产品的好坏！这个会开的我是特别的困到后来我就要站起来，我听才可以，要不然就得睡着，下午的时候继续做c的项目。
\
基本上做到晚上快下班的时候才做了差不多。
\
然后又跟技术的老大一起开了个技术评审会，
\
晚上就是看了一个电影，然后就完事儿了。
\
下午的时候快四点的时候。许燕找我聊天，她说她去滑雪了，去了一趟终极道，结果特别怂，
\
然后全程就在初级打完他的两个朋友滑雪很厉害，然后都不带他玩，
\
我就约她，下回跟我一起玩吧，他答应着了。
\
我说那等你有空的时候你约我他答应了，所以，之后我就不管了，就看他什么时候约我了，既然我已经把主动权交给他了，我就不做舔狗了。
\
跟他聊天，下午刚开始的时候，我是秒回到后来的时候，确实因为工作有点忙，然后就回的慢了一些，最后他发了几段语音，我就隔了半个小时之后我就只来得及回了一个，在之后就没有回复了。
\
晚上看完电影之后，我又发了一个朋友圈，朋友圈里面王倩给我评论了，就是保定的往前之前他从来不带评论，我朋友圈也从来不点赞。
\
我今天就在朋友圈发了一下电影，半个喜剧里面的台词就是
\
我不是不知道现实的这个世界是什么样子，我只是想试试这样可不可以就是这样一段话，
\
然后引起了很多人的返乡，
\
今天。
\
也算是明白了不少，
\
首先不能做舔狗要做自己。
\
追女生，酱不能用追这个字，很多时候不管是做生意还是谈恋爱，虽然有个为什么，
\
总需要从对方的角度来思考一下人家。为什么要跟我谈恋爱？
\
为什么不是和别人去谈恋爱？我能给他什么？他能从我这里得到什么？这就是现实，
\
而这是逃脱不了的现实。
\
那么好好想一下，
\
一个女生可以从我这里得到什么，我又可以给人家什么呢？
\
我可以给他金钱吗？不可以给他地位吗？不可以给他带房子吗？豪车吗？都不可以。
\
\
\
我想我可以给他。温馨的生活。我想我可以给他健康的生活方式。我相信我可以给他。好好做自己的机会。我可以给他尊重。
\
我也可以给他。
\
所有的支持我可以给他问呢，给他关心，给他拐，给他独立，给他个性。
*