* 一周前的时候，和许言说过要约滑雪的事情，说的是我在古崖居的比赛之后就有大把的时间用来滑雪了，在本周一早上，我觉得这周还能滑雪的，就在微信上问了许言这周五要不要去滑雪，等了一天没有等到回复，等到周二的时候，她才突然冒出来一句，滑雪、约。搞得我都有点无语了，不过她觉得滑雪还是有些贵，我就说如果陪我一起滑两天的滑，我就请她了。她说也能滑两天的。我在周三就赶紧的请假，订酒店。因为男女有别，每人一间双床标间。考虑到住宿环境的问题，就选在了稍微远一些的镇上吧，

没有去住农家院。价钱差不多，只是路程远了七八公里。
\
昨天早上我先跑了步，然后收拾收拾，十点多出门，我寻思着，许言这次肯定还会迟到，因为是两点半开始，我故意约到了两点。这样有个缓冲的时间。没想到我还在地铁上的时候，她就跟我说她快到了。原来她算了下时间可能来不及，就直接打车过来了。我说那等我下，我出了地铁也打车过去吧。到了雪场先去吃了饭，然后在餐厅等了一个多小时，才能去兑换雪票开始滑雪。因为穿鞋换装备耽误了时间，所以下午快三点了才开始滑，也就是滑了一个多小时的时间，雪场就开始清理日场的人，为了腾出空间来压雪。下午也就是滑了四五次的样子。前两次就是为了找找感觉，第一圈的时候后刃推坡都费劲，后面学了下前刃推坡。两趟的时候就能滑出去比较远的距离了。最后一圈的时候，试着教了教许言如何滑前刃。不过跌倒的太频繁，后半程就放弃了前刃，直接用后刃。
\
晚上在餐厅吃了份饺子，就回到了战场。在吃饭的时候，我用小票纸给她讲解了下前刃刹车和左右转向的原理以及换刃的示意。晚上滑了13次以上。有一半的时间我都是在帮她录视频。有时候正着录，有时候倒着录。有一次我是倒着录的，本来她在我的后面，我倒着录刚刚好。结果她突然加速，跑到我前面去了，我只好也前刃加速，并且半转身去录她。结果她慢下来了，我想慢的时候身体没有掌握好平衡。直接摔出去了，包括手机。当时我感觉脏腑器官被车撞了似的。隔了好一会才好点。直到晚上回到酒店才没有感觉，不过我还是尝试了大S换刃和直线换刃，虽然有的成功有的不成功，但是能知道原理了，在有差不多的速度的基础上，不断地切换前后刃，同时切换离心力的方向以及重心的方向。许言在晚上的时候已经可以比较流利的使用前刃推坡以及落叶飘了，对于转弯换刃也有了一定的了解，能有意识的从直板到前刃刹车。
\
计划今天和她把前刃+后刃+换刃再练的熟练一些。如果有时间的话，练一下其他的，例如板头/尾平衡，
\
今早5点半起床，先给高雅打电话，紧接着就墨迹了6分钟，然后穿衣服出去跑步，差不多跑了5公里吧。
\
\
到了雪场里面，租了套雪板、鞋子、护具啥的，没想到许言居然因为护膝和鞋子的颜色特别搭配还有雪镜的颜色，特别的开心。
\
下午的时候大多数时间是在拍照，拍视频。其实我也就没咋联系。
\
说实话，今天挺开心的，玩的很欢。也很快乐，许言也给我拍了视频。不过到了傍晚还是很失落，毕竟快乐是那么的短暂。两天的开心，瞬间就变成不开心了。尤其是晚上她在微信上的回答不冷不热的，还是有些失落。
\
有些习惯不是说戒掉就能戒掉的，喜欢许言就是这样。
\
我的痛苦也不知道和谁说出来，心中所痛，说与谁人听。
\
至少今天许言不再那么一直自私下去了，还知道主动的说帮我录视频，虽然我上午的时候说过一次。晚上在公交车上的时候闻了一下我的名字。我在微信上告诉了她。
\
以后反正也不闲聊了，要么不聊天，要么就是约出来。她还说要教我游泳，等到明年三四月份的时候吧
\
<<>>
*